import { Navbar } from '@/components/landing/Navbar';
import { Footer } from '@/components/landing/Footer';
import { motion } from 'framer-motion';
import { ShieldCheck, Terminal, AlertCircle, Laptop, Command } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import heroAbstractBg from '@/assets/hero-abstract-bg.jpg';

export default function VerificationGuide() {
    return (
        <main className="min-h-screen bg-[#0a0a0a] text-foreground overflow-x-hidden selection:bg-cyan-500/30">
            <Navbar />

            <section className="pt-32 pb-24 px-6 relative min-h-screen flex flex-col justify-center">
                {/* Background Effects */}
                <div className="absolute inset-0 bg-gradient-to-b from-black/0 via-black/50 to-black pointer-events-none" />

                {/* Ambient Background */}
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-cyan-500/10 rounded-full blur-[120px] pointer-events-none" />
                <div className="absolute bottom-0 right-0 w-[800px] h-[600px] bg-blue-600/10 rounded-full blur-[120px] pointer-events-none" />

                <div className="container mx-auto max-w-4xl relative z-10">

                    {/* Header */}
                    <div className="text-center mb-16">
                        <motion.div
                            initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                            className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-yellow-500/30 bg-yellow-500/10 mb-6"
                        >
                            <AlertCircle className="w-4 h-4 text-yellow-500" />
                            <span className="text-xs font-semibold text-yellow-500 uppercase tracking-wide">In-house tool coming soon</span>
                        </motion.div>

                        <motion.h1
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="text-4xl md:text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-b from-white to-white/60 mb-6"
                        >
                            How to Verify Authenticity
                        </motion.h1>

                        <motion.p
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.1 }}
                            className="text-xl text-zinc-400 max-w-2xl mx-auto leading-relaxed"
                        >
                            Every Effortless certificate is chemically bound to the final document.
                            You can prove this connection independently using standard system tools.
                        </motion.p>
                    </div>

                    {/* Explanation Card */}
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.2 }}
                        className="p-8 rounded-2xl bg-zinc-900/50 border border-white/5 backdrop-blur-sm mb-16"
                    >
                        <div className="grid md:grid-cols-2 gap-8 items-center">
                            <div>
                                <h3 className="text-2xl font-bold text-white mb-4">The Logic</h3>
                                <p className="text-zinc-400 leading-relaxed mb-4">
                                    When a session ends, we calculate the <span className="text-cyan-400">SHA-256 hash</span> (digital fingerprint) of the final PDF generated by Effortless.
                                    This hash is stamped onto the permanent certificate.
                                </p>
                                <p className="text-zinc-400 leading-relaxed">
                                    <strong className="text-white">Proof Rule:</strong> If the hash of the Effortless-generated file matches the hash on the certificate, the file is authentic and unaltered.
                                </p>
                            </div>
                            <div className="bg-black/40 rounded-xl p-6 border border-white/5 font-mono text-sm">
                                <div className="text-zinc-500 mb-2">// How it connects</div>
                                <div className="text-emerald-500">Certificate Hash:</div>
                                <div className="text-zinc-300 break-all mb-4">e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</div>

                                <div className="flex items-center gap-4 my-2">
                                    <div className="h-px bg-zinc-800 flex-1" />
                                    <div className="text-zinc-600">MUST MATCH</div>
                                    <div className="h-px bg-zinc-800 flex-1" />
                                </div>

                                <div className="text-cyan-500">Document Hash:</div>
                                <div className="text-zinc-300 break-all">e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</div>
                            </div>
                        </div>
                    </motion.div>


                    {/* Instructions Tabs */}
                    <div className="mb-12">
                        <h3 className="text-2xl font-bold text-center mb-8">Choose Your Platform</h3>

                        <Tabs defaultValue="windows" className="w-full max-w-3xl mx-auto">
                            <TabsList className="grid w-full grid-cols-2 bg-zinc-900/80 mb-8 p-1 rounded-xl">
                                <TabsTrigger value="windows" className="data-[state=active]:bg-zinc-800 data-[state=active]:text-white rounded-lg py-3">
                                    <Laptop className="w-4 h-4 mr-2" /> Windows
                                </TabsTrigger>
                                <TabsTrigger value="mac" className="data-[state=active]:bg-zinc-800 data-[state=active]:text-white rounded-lg py-3">
                                    <Command className="w-4 h-4 mr-2" /> Mac / Linux
                                </TabsTrigger>
                            </TabsList>

                            <TabsContent value="windows">
                                <InstructionCard
                                    step1="Open Command Prompt or PowerShell."
                                    step2="Navigate to the folder containing your document."
                                    step3="Run the following command:"
                                    command="certutil -hashfile my_document.pdf SHA256"
                                    note="Replace 'my_document.pdf' with your actual filename."
                                />
                            </TabsContent>

                            <TabsContent value="mac">
                                <InstructionCard
                                    step1="Open the Terminal app."
                                    step2="Navigate to the folder containing your document."
                                    step3="Run the following command:"
                                    command="shasum -a 256 my_document.pdf"
                                    note="Replace 'my_document.pdf' with your actual filename."
                                />
                            </TabsContent>
                        </Tabs>
                    </div>

                    <div className="text-center text-zinc-500 text-sm max-w-lg mx-auto">
                        <p>Our dedicated verification tool is in development and will allow drag-and-drop verification directly in the browser.</p>
                    </div>

                </div>
            </section>

            <Footer />
        </main>
    );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function InstructionCard({ step1, step2, step3, command, note }: any) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-zinc-900 border border-zinc-800 rounded-2xl p-8"
        >
            <ol className="space-y-6 list-decimal list-inside text-zinc-300">
                <li className="pl-2">
                    <span className="font-semibold text-white">{step1}</span>
                </li>
                <li className="pl-2">
                    <span className="font-semibold text-white">{step2}</span>
                </li>
                <li className="pl-2">
                    <span className="font-semibold text-white">{step3}</span>
                    <div className="mt-4 bg-black rounded-lg p-4 font-mono text-sm border border-zinc-800 flex items-center justify-between group">
                        <code className="text-cyan-400">{command}</code>
                    </div>
                </li>
            </ol>
            <p className="mt-6 text-sm text-zinc-500 italic pl-6 border-l-2 border-zinc-800">
                Note: {note}
            </p>
        </motion.div>
    );
}
